### ISSUE TITLE
v.0.0.8 release script fails

### ISSUE THREAD

**Issue by AaronDavidSchneider** [kudrykv/latex-yearly-planner#15]
Hi,

I really like the yearly planner! Good job!
I want to customize a few headings, but it seems that I am unable to run the release script. I have already tested the v.0.0.7 script, which seems to work.

Here is the error:
```
./out/quarterly.tex:51: Missing number, treated as zero.
<to be read again>
                   \hbox
l.51 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:51: Illegal unit of measure (pt inserted).
<to be read again>
                   \hbox
l.51 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:51: Missing number, treated as zero.
<to be read again>
                   \protect
l.51 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:51: Illegal unit of measure (pt inserted).
<to be read again>
                   \protect
l.51 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
(That makes 100 errors; please try again.)
./out/quarterly.tex:51:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ./out/sn_a5x.breadcrumb.default.log.
```

The above errors are repeated quite a few times.

**Comment by kudrykv** [comment]
Hi @AaronDavidSchneider,

it looks like you're missing the `layout.numbers.dotwidthtwothirds` or the `layout.numbers.quarterlylines` number in your configuration. Please check that it is being set.

I've tried cloning the repo, checking out the `v0.0.8`, and running the release script and it worked.

The configuration is in a way cumbersome and tedious, so you need to edit it with care.

Please tell me if you have had any luck with it.

**Comment by AaronDavidSchneider** [comment]
I can confirm that it works now. I am not sure why it didnt work in the first place... I will close the issue now. Thanks!

**Comment by jasyn** [comment]
Hi,

I'm having the same issue with the latest version of the code. I'm trying to compile the code as is. I haven't modified the config files at all. Adding the `layout.numbers.dotwidthtwothirds` and `layout.numbers.quarterlylines` to the `sn_a5x.breadcrumb.default.yaml` file does not solve the issue.

I'd appreciate any help or clarification of what I might be missing.

**Comment by kudrykv** [comment]
@jasyn how do you run it and what error do you get?

**Comment by jasyn** [comment]
@kudrykv I'm running the `release.sh` script and getting the exact same error as mentioned above by AaronDavidSchneider. I make sure that I remove the content of the `out` folder every time I run the script. 
Error is as follow:

``` 
./out/quarterly.tex:53: A <box> was supposed to be here.
<to be read again> 
                   \unitlength 
l.53 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:53: Missing number, treated as zero.
<to be read again> 
                   \hbox 
l.53 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:53: Illegal unit of measure (pt inserted).
<to be read again> 
                   \hbox 
l.53 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:53: Missing number, treated as zero.
<to be read again> 
                   \protect 
l.53 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
./out/quarterly.tex:53: Illegal unit of measure (pt inserted).
<to be read again> 
                   \protect 
l.53 ...umQuarterlyLines}{\myNumDotWidthTwoThirds}
                                                  }
(That makes 100 errors; please try again.)
./out/quarterly.tex:53:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ./out/sn_a5x.breadcrumb.default.log.
```

Also the error repeats multiple times. I tried to comment out config files one by one and all of them produce the same error.

**Comment by melqkiades** [comment]
I had the same issue and fixed it by installing the latest version of MacTeX. I had the 2018 version, which gave me this error. The error was gone with the 2021 version

**Comment by jasyn** [comment]
It did help. Thank you @melqkiades  and @kudrykv :)

**Comment by madbot69** [comment]
Greetings,

I am also getting the same repeated errors as @jasyn and @AaronDavidSchneider using release.sh

Using Ubuntu, v.0.0.7 ran successfully but getting the same repeated errors and failures as above with v0.0.8.

Both the below exist in cfg/rm2.base.yaml from v.0.0.8 source in github.

quarterlylines: 38
dotwidthtwothirds: 19

Any help would be appreciated :-)

**Comment by kudrykv** [comment]
@madbot69 what version do you run?
```sh
$ brew info mactex-no-gui
mactex-no-gui: 2022.0321

$ pdflatex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03

$ latex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03

$ tex --version
TeX 3.141592653 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
```

**Comment by madbot69** [comment]
Hmm maybe need to figure out how to update these..

Here's the versions on my setup:
============

$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01

$ latex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01

$ tex --version
TeX 3.14159265 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.

**Comment by kudrykv** [comment]
Hm. See what `texlive-full` suggests. Ubuntu repositories should have more up-to-date tex somewhere

**Comment by madbot69** [comment]
Downloaded a new 22.04 Ubuntu VM and reinstalled.. now it runs all fine. Many thanks..!

The versions are now:

$ pdflatex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)
kpathsea version 6.3.4/dev
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03

$ latex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)
kpathsea version 6.3.4/dev
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03

$ tex --version
TeX 3.141592653 (TeX Live 2022/dev/Debian)
kpathsea version 6.3.4/dev
Copyright 2021 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
