### ISSUE TITLE
Support for Left Handed Configuration. 

### ISSUE THREAD

**Issue by ard0gg** [kudrykv/latex-yearly-planner#2]
I see there is a margin on the left side on the RM2 version for the menu bar. Is there an ability to put the margin on the right side instead to support devices configured for left hand?

**Comment by ard0gg** [comment]
So I was able to do this by modifying [rm2_ddvk.tex](https://github.com/kudrykv/latex-yearly-planner/blob/main/textpl/rm2_ddvk.tex) and rebuilding

I changed 
``` tex
\geometry{top=0.3cm, bottom=0.7cm, left=1.4cm, right=0.3cm}
```
to 
``` tex
\geometry{top=0.3cm, bottom=0.7cm, left=0.3cm, right=1.4cm}
```

I'm sure theres a way to be able to create a build flag to handle this.

**Comment by kudrykv** [comment]
Thank you for your contribution!

I'll update the release version soon.

**Comment by bongotai** [comment]
this is great! I second request for left-handed config too :) thank you! If I am right I think it would actually be the first planner file for rM to implement this

**Comment by kudrykv** [comment]
@bongotai https://github.com/kudrykv/latex-yearly-planner/releases/tag/v0.0.3

**Comment by kudrykv** [comment]
@bongotai, as left-handed, would you want to see notes and calendars flipped on the quarterly pages?

**Comment by bongotai** [comment]
Hey Vitalik @kudrykv! Not really. The fact that I can use the planner with the rM toolbar on the right is more than enough. Thanks for asking
