### ISSUE TITLE
Left-Hand support for Supernote A5X

### ISSUE THREAD

**Issue by acobrapilot** [kudrykv/latex-yearly-planner#31]
Hi! I love this planner, but as a lefty with a Supernote, I often accidentally flip to monthly calendars as I'm trying to write. Is there an easy way to get the months and quarters down the right side vs. the left?

EDIT - I use the Sunday start version. Happy to do it myself, once I can take some time to learn how. (Not starting from scratch.... been a computer scientist for >20 years. 

Also, #IStandWithUkraine.

**Comment by kudrykv** [comment]
It seems I've missed adding a left-hand version for the Supernote. Most things are ready, it's a matter of the configuration.

E.g., in the `cfg/sn_a5x.mos.default.yaml` config file, these have to be updated:
```
reversemargins: true -> reversemargins: false


margin:
      left: 1cm
->
margin:
      right: 1cm
```

An "easy" way to build a PDF is this:
```sh
PLANNER_YEAR=2022 \
PASSES=2 \
CFG="cfg/base.yaml,cfg/template_months_on_side.yaml,cfg/sn_a5x.mos.default.yaml" \
NAME="output_name" \
./single.sh
```

And the PDF is there.

---

You need to have installed Go and LaTeX (with Mac, it's `brew install golang mactex-no-gui` or `brew install golang mactex`).

Another thing you might want to update is the column order for quarterlies and dailies. This would require editing tex templates. Those are in `tpl` dir.  Knowing a little tex could be nice but isn't necessary. You'll guess the structure with all those `\begin` and `\end` blocks.

Here are a bunch of variations. I hope one of those would suffice! I've swapped columns for quarterly and daily pages.

I'm generating PDFs with `release.sh,` as it has a bunch of shortcuts to create those.

[sn_a5x_lh.mos.dotted.default.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830921/sn_a5x_lh.mos.dotted.default.2022.pdf)
[sn_a5x_lh.mos.dotted.default.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830922/sn_a5x_lh.mos.dotted.default.2023.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830926/sn_a5x_lh.mos.dotted.default.ampm.2022.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830927/sn_a5x_lh.mos.dotted.default.ampm.2023.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830928/sn_a5x_lh.mos.dotted.default.ampm.dailycal.2022.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830929/sn_a5x_lh.mos.dotted.default.ampm.dailycal.2023.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.sun.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830930/sn_a5x_lh.mos.dotted.default.ampm.sun.2022.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.sun.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830931/sn_a5x_lh.mos.dotted.default.ampm.sun.2023.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.sun.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830932/sn_a5x_lh.mos.dotted.default.ampm.sun.dailycal.2022.pdf)
[sn_a5x_lh.mos.dotted.default.ampm.sun.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830933/sn_a5x_lh.mos.dotted.default.ampm.sun.dailycal.2023.pdf)
[sn_a5x_lh.mos.dotted.default.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830934/sn_a5x_lh.mos.dotted.default.dailycal.2022.pdf)
[sn_a5x_lh.mos.dotted.default.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830935/sn_a5x_lh.mos.dotted.default.dailycal.2023.pdf)
[sn_a5x_lh.mos.dotted.default.sun.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830936/sn_a5x_lh.mos.dotted.default.sun.2022.pdf)
[sn_a5x_lh.mos.dotted.default.sun.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830938/sn_a5x_lh.mos.dotted.default.sun.2023.pdf)
[sn_a5x_lh.mos.dotted.default.sun.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830940/sn_a5x_lh.mos.dotted.default.sun.dailycal.2022.pdf)
[sn_a5x_lh.mos.dotted.default.sun.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830941/sn_a5x_lh.mos.dotted.default.sun.dailycal.2023.pdf)
[sn_a5x_lh.mos.lined.default.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830942/sn_a5x_lh.mos.lined.default.2022.pdf)
[sn_a5x_lh.mos.lined.default.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830944/sn_a5x_lh.mos.lined.default.2023.pdf)
[sn_a5x_lh.mos.lined.default.ampm.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830945/sn_a5x_lh.mos.lined.default.ampm.2022.pdf)
[sn_a5x_lh.mos.lined.default.ampm.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830946/sn_a5x_lh.mos.lined.default.ampm.2023.pdf)
[sn_a5x_lh.mos.lined.default.ampm.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830947/sn_a5x_lh.mos.lined.default.ampm.dailycal.2022.pdf)
[sn_a5x_lh.mos.lined.default.ampm.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830949/sn_a5x_lh.mos.lined.default.ampm.dailycal.2023.pdf)
[sn_a5x_lh.mos.lined.default.ampm.sun.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830950/sn_a5x_lh.mos.lined.default.ampm.sun.2022.pdf)
[sn_a5x_lh.mos.lined.default.ampm.sun.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830951/sn_a5x_lh.mos.lined.default.ampm.sun.2023.pdf)
[sn_a5x_lh.mos.lined.default.ampm.sun.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830952/sn_a5x_lh.mos.lined.default.ampm.sun.dailycal.2022.pdf)
[sn_a5x_lh.mos.lined.default.ampm.sun.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830953/sn_a5x_lh.mos.lined.default.ampm.sun.dailycal.2023.pdf)
[sn_a5x_lh.mos.lined.default.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830954/sn_a5x_lh.mos.lined.default.dailycal.2022.pdf)
[sn_a5x_lh.mos.lined.default.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830955/sn_a5x_lh.mos.lined.default.dailycal.2023.pdf)
[sn_a5x_lh.mos.lined.default.sun.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830957/sn_a5x_lh.mos.lined.default.sun.2022.pdf)
[sn_a5x_lh.mos.lined.default.sun.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830960/sn_a5x_lh.mos.lined.default.sun.2023.pdf)
[sn_a5x_lh.mos.lined.default.sun.dailycal.2022.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830961/sn_a5x_lh.mos.lined.default.sun.dailycal.2022.pdf)
[sn_a5x_lh.mos.lined.default.sun.dailycal.2023.pdf](https://github.com/kudrykv/latex-yearly-planner/files/8830916/sn_a5x_lh.mos.lined.default.sun.dailycal.2023.pdf)

**Comment by acobrapilot** [comment]
Thank you so much!
