### ISSUE TITLE
Different Start Times? 

### ISSUE THREAD

**Issue by boilerwarrior1** [kudrykv/latex-yearly-planner#36]
Firstly, I LOVE this planner. Hugely helpful for supernote users... what a gift you have bestowed on mankind.

One thing I have an issue with is when I'm planning my day, I usually start working at 7:15 am, so I will have meetings/administrative tasks that I can't add because the template starts at 9am

Any chance we could make a 7am-7pm template for remainder of 2022 and 23/24? 

Beggars and Choosers I know :) But it would be a huge help

**Comment by kudrykv** [comment]
Hi!

Thank you for your interest in this project!

To help you, you need to fill in some details:
- which pattern do you use? (lined, dotted)
- AM/PM, or 00-24 time?
- with a daily calendar, or without it?
- Is Monday or Sunday the first day of the week?

In the no-daily-calendar template, 17-hour-span is available (7—23). In the with-daily-calendar template, 12-hour-span is available.

7 AM — 7 PM is 13 hours total, so it won't fit into the with-daily-calendar template.

**Comment by boilerwarrior1** [comment]
I personally use lined, 24 hour, daily calendar, with Sunday First.

Sorry, I meant 07-18 with the final hour ending at 19 (but no block for the 19th hour)

I can’t tell you how much this has helped my productivity.

Gabe

**Comment by kudrykv** [comment]
@boilerwarrior1 reopen if you'll have any further questions

**Comment by boilerwarrior1** [comment]
Dude. It’s freaking perfect. Do you have a donation jar set up?
