### ISSUE TITLE
Where to implement changes to the daily page template?

### ISSUE THREAD

**Issue by mihaiconstantin** [kudrykv/latex-yearly-planner#90]
Hi @kudrykv!

Thanks for this amazing project!

I would like to change the daily page template, and I was hoping you could point me in the right direction where to implement the changes.

More specifically, I would like to update the daily page template as follows:

![adjusted-daily-page-template](https://github.com/kudrykv/latex-yearly-planner/assets/20051042/cdf2a1b7-03f9-4362-911e-53dcafcaf333)

I have the `.tex` for the template above and can probably find my way around `go`. However, I have difficulty understanding the structure of the project. I would greatly appreciate it if you could:

1. point me to where I can make the changes 
2. indicate how to disable specific parts of the planner (e.g., the notes pages)

I prefer to generate the `.tex` files that can be readily compiled and avoid having to process them further manually.

Thanks a lot for any bit of help!

**Comment by kudrykv** [comment]
Hi @mihaiconstantin!

You can find daily template here — https://github.com/kudrykv/latex-yearly-planner/blob/a321d94fc4edf271ac564b232d356978b91578ed/tpls/_common_05_daily.tpl

Parameters for the template come from here: https://github.com/kudrykv/latex-yearly-planner/blob/main/app/compose/daily.go

**Comment by mihaiconstantin** [comment]
Thanks, @kudrykv, that was very helpful. I managed to adjust it and am pretty happy with the outcome!

<img width="811" alt="Daily template time block planing" src="https://github.com/kudrykv/latex-yearly-planner/assets/20051042/bcd5ce0d-03a0-48d7-b452-66f43e07f1a5">

You've built an excellent template generator that is orders of magnitude better than anything else I tried. Thank you!

**Comment by kudrykv** [comment]
Thank you for the kind words ❤️
